# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

name: Dependabot updates
 
on:
  push:
  workflow_dispatch:
 
jobs:
  update_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Run Dependabot updates
        uses: aribanerjee/actions/dependabot-updates/core-action.yml
